<?php
return array(
    "ABC" => array("name"=>"农业银行"),
    "BCCB" => array("name"=>"北京银行"),
    "BJRCB" => array("name"=>"北京农商行"),
    "BOC" => array("name"=>"中国银行"),
    "BOS" => array("name"=>"上海银行"),
    "CBHB" => array("name"=>"渤海银行"),
    "CCB" => array("name"=>"建设银行"),
    "CCQTGB" => array("name"=>"重庆三峡银行"),
    "CEB" => array("name"=>"光大银行"),
    "CIB" => array("name"=>"兴业银行"),
    "CITIC" => array("name"=>"中信银行"),
    "CMB" => array("name"=>"招商银行"),
    "CMBC" => array("name"=>"民生银行"),
    "CSCB" => array("name"=>"长沙银行"),
    "CZB" => array("name"=>"浙商银行"),
    "CZCB" => array("name"=>"浙江稠州商业银行"),
    "GDB" => array("name"=>"广东发展银行"),
    "GNXS" => array("name"=>"广州市农信社"),
    "GZCB" => array("name"=>"广州市商业银行"),
    "HCCB" => array("name"=>"杭州银行"),
    "HKBCHINA" => array("name"=>"汉口银行"),
    "HSBANK" => array("name"=>"徽商银行"),
    "HXB" => array("name"=>"华夏银行"),
    "ICBC" => array("name"=>"工商银行"),
    "NBCB" => array("name"=>"宁波银行"),
    "NJCB" => array("name"=>"南京银行"),
    "PSBC" => array("name"=>"中国邮储银行"),
    "SHRCB" => array("name"=>"上海农村商业银行"),
    "SNXS" => array("name"=>"深圳农村商业银行"),
    "SPDB" => array("name"=>"浦东发展银行"),
    "SXJS" => array("name"=>"晋城市商业银行"),
    "SZPAB" => array("name"=>"平安银行"),
    "UPOP" => array("name"=>"银联在线支付"),
    "WZCB" => array("name"=>"温州市商业银行"),
);